//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadati relazioni EDM

[assembly: EdmRelationshipAttribute("TitheDBModel", "FK__TitheLogs__Tithe__08EA5793", "Tither", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Woodensoft.TitherPro.Domain.Contexts.Tither), "TitheLogs", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Woodensoft.TitherPro.Domain.Contexts.TitheLog), true)]

#endregion

namespace Woodensoft.TitherPro.Domain.Contexts
{
    #region Contesti
    
    /// <summary>
    /// Nessuna documentazione sui metadati disponibile.
    /// </summary>
    public partial class TitheDBEntities : ObjectContext
    {
        #region Costruttori
    
        /// <summary>
        /// Inizializza un nuovo oggetto TitheDBEntities utilizzando la stringa di connessione trovata nella sezione 'TitheDBEntities' del file di configurazione dell'applicazione.
        /// </summary>
        public TitheDBEntities() : base("name=TitheDBEntities", "TitheDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inizializzare un nuovo oggetto TitheDBEntities.
        /// </summary>
        public TitheDBEntities(string connectionString) : base(connectionString, "TitheDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inizializzare un nuovo oggetto TitheDBEntities.
        /// </summary>
        public TitheDBEntities(EntityConnection connection) : base(connection, "TitheDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Metodi parziali
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Proprietà ObjectSet
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        public ObjectSet<TitheLog> TitheLogs
        {
            get
            {
                if ((_TitheLogs == null))
                {
                    _TitheLogs = base.CreateObjectSet<TitheLog>("TitheLogs");
                }
                return _TitheLogs;
            }
        }
        private ObjectSet<TitheLog> _TitheLogs;
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        public ObjectSet<Tither> Tithers
        {
            get
            {
                if ((_Tithers == null))
                {
                    _Tithers = base.CreateObjectSet<Tither>("Tithers");
                }
                return _Tithers;
            }
        }
        private ObjectSet<Tither> _Tithers;
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region Metodi AddTo
    
        /// <summary>
        /// Metodo deprecato per l'aggiunta di un nuovo oggetto all'elemento EntitySet TitheLogs. Utilizzare il metodo .Add della proprietà associata ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToTitheLogs(TitheLog titheLog)
        {
            base.AddObject("TitheLogs", titheLog);
        }
    
        /// <summary>
        /// Metodo deprecato per l'aggiunta di un nuovo oggetto all'elemento EntitySet Tithers. Utilizzare il metodo .Add della proprietà associata ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToTithers(Tither tither)
        {
            base.AddObject("Tithers", tither);
        }
    
        /// <summary>
        /// Metodo deprecato per l'aggiunta di un nuovo oggetto all'elemento EntitySet Users. Utilizzare il metodo .Add della proprietà associata ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entità
    
    /// <summary>
    /// Nessuna documentazione sui metadati disponibile.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TitheDBModel", Name="TitheLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TitheLog : EntityObject
    {
        #region Metodo factory
    
        /// <summary>
        /// Creare un nuovo oggetto TitheLog.
        /// </summary>
        /// <param name="titheLogId">Valore iniziale della proprietà TitheLogId.</param>
        /// <param name="titheDate">Valore iniziale della proprietà TitheDate.</param>
        /// <param name="dateEntered">Valore iniziale della proprietà DateEntered.</param>
        /// <param name="titheAmount">Valore iniziale della proprietà TitheAmount.</param>
        public static TitheLog CreateTitheLog(global::System.Int64 titheLogId, global::System.DateTime titheDate, global::System.DateTime dateEntered, global::System.Decimal titheAmount)
        {
            TitheLog titheLog = new TitheLog();
            titheLog.TitheLogId = titheLogId;
            titheLog.TitheDate = titheDate;
            titheLog.DateEntered = dateEntered;
            titheLog.TitheAmount = titheAmount;
            return titheLog;
        }

        #endregion
        #region Proprietà primitive
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TitheLogId
        {
            get
            {
                return _TitheLogId;
            }
            set
            {
                if (_TitheLogId != value)
                {
                    OnTitheLogIdChanging(value);
                    ReportPropertyChanging("TitheLogId");
                    _TitheLogId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TitheLogId");
                    OnTitheLogIdChanged();
                }
            }
        }
        private global::System.Int64 _TitheLogId;
        partial void OnTitheLogIdChanging(global::System.Int64 value);
        partial void OnTitheLogIdChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime TitheDate
        {
            get
            {
                return _TitheDate;
            }
            set
            {
                OnTitheDateChanging(value);
                ReportPropertyChanging("TitheDate");
                _TitheDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TitheDate");
                OnTitheDateChanged();
            }
        }
        private global::System.DateTime _TitheDate;
        partial void OnTitheDateChanging(global::System.DateTime value);
        partial void OnTitheDateChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateEntered
        {
            get
            {
                return _DateEntered;
            }
            set
            {
                OnDateEnteredChanging(value);
                ReportPropertyChanging("DateEntered");
                _DateEntered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateEntered");
                OnDateEnteredChanged();
            }
        }
        private global::System.DateTime _DateEntered;
        partial void OnDateEnteredChanging(global::System.DateTime value);
        partial void OnDateEnteredChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TitheAmount
        {
            get
            {
                return _TitheAmount;
            }
            set
            {
                OnTitheAmountChanging(value);
                ReportPropertyChanging("TitheAmount");
                _TitheAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TitheAmount");
                OnTitheAmountChanged();
            }
        }
        private global::System.Decimal _TitheAmount;
        partial void OnTitheAmountChanging(global::System.Decimal value);
        partial void OnTitheAmountChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TitherId
        {
            get
            {
                return _TitherId;
            }
            set
            {
                OnTitherIdChanging(value);
                ReportPropertyChanging("TitherId");
                _TitherId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TitherId");
                OnTitherIdChanged();
            }
        }
        private Nullable<global::System.Int32> _TitherId;
        partial void OnTitherIdChanging(Nullable<global::System.Int32> value);
        partial void OnTitherIdChanged();

        #endregion
    
        #region Proprietà di navigazione
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TitheDBModel", "FK__TitheLogs__Tithe__08EA5793", "Tither")]
        public Tither Tither
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tither>("TitheDBModel.FK__TitheLogs__Tithe__08EA5793", "Tither").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tither>("TitheDBModel.FK__TitheLogs__Tithe__08EA5793", "Tither").Value = value;
            }
        }
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tither> TitherReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tither>("TitheDBModel.FK__TitheLogs__Tithe__08EA5793", "Tither");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tither>("TitheDBModel.FK__TitheLogs__Tithe__08EA5793", "Tither", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Nessuna documentazione sui metadati disponibile.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TitheDBModel", Name="Tither")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tither : EntityObject
    {
        #region Metodo factory
    
        /// <summary>
        /// Creare un nuovo oggetto Tither.
        /// </summary>
        /// <param name="titherId">Valore iniziale della proprietà TitherId.</param>
        /// <param name="lastName">Valore iniziale della proprietà LastName.</param>
        /// <param name="firstName">Valore iniziale della proprietà FirstName.</param>
        /// <param name="dateJoined">Valore iniziale della proprietà DateJoined.</param>
        public static Tither CreateTither(global::System.Int32 titherId, global::System.String lastName, global::System.String firstName, global::System.DateTime dateJoined)
        {
            Tither tither = new Tither();
            tither.TitherId = titherId;
            tither.LastName = lastName;
            tither.FirstName = firstName;
            tither.DateJoined = dateJoined;
            return tither;
        }

        #endregion
        #region Proprietà primitive
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TitherId
        {
            get
            {
                return _TitherId;
            }
            set
            {
                if (_TitherId != value)
                {
                    OnTitherIdChanging(value);
                    ReportPropertyChanging("TitherId");
                    _TitherId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TitherId");
                    OnTitherIdChanged();
                }
            }
        }
        private global::System.Int32 _TitherId;
        partial void OnTitherIdChanging(global::System.Int32 value);
        partial void OnTitherIdChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateJoined
        {
            get
            {
                return _DateJoined;
            }
            set
            {
                OnDateJoinedChanging(value);
                ReportPropertyChanging("DateJoined");
                _DateJoined = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateJoined");
                OnDateJoinedChanged();
            }
        }
        private global::System.DateTime _DateJoined;
        partial void OnDateJoinedChanging(global::System.DateTime value);
        partial void OnDateJoinedChanged();

        #endregion
    
        #region Proprietà di navigazione
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TitheDBModel", "FK__TitheLogs__Tithe__08EA5793", "TitheLogs")]
        public EntityCollection<TitheLog> TitheLogs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TitheLog>("TitheDBModel.FK__TitheLogs__Tithe__08EA5793", "TitheLogs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TitheLog>("TitheDBModel.FK__TitheLogs__Tithe__08EA5793", "TitheLogs", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Nessuna documentazione sui metadati disponibile.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TitheDBModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Metodo factory
    
        /// <summary>
        /// Creare un nuovo oggetto User.
        /// </summary>
        /// <param name="userId">Valore iniziale della proprietà UserId.</param>
        /// <param name="username">Valore iniziale della proprietà Username.</param>
        /// <param name="password">Valore iniziale della proprietà Password.</param>
        /// <param name="isAdmin">Valore iniziale della proprietà IsAdmin.</param>
        /// <param name="active">Valore iniziale della proprietà Active.</param>
        public static User CreateUser(global::System.Int32 userId, global::System.String username, global::System.String password, global::System.Boolean isAdmin, global::System.Boolean active)
        {
            User user = new User();
            user.UserId = userId;
            user.Username = username;
            user.Password = password;
            user.IsAdmin = isAdmin;
            user.Active = active;
            return user;
        }

        #endregion
        #region Proprietà primitive
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAdmin
        {
            get
            {
                return _IsAdmin;
            }
            set
            {
                OnIsAdminChanging(value);
                ReportPropertyChanging("IsAdmin");
                _IsAdmin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAdmin");
                OnIsAdminChanged();
            }
        }
        private global::System.Boolean _IsAdmin;
        partial void OnIsAdminChanging(global::System.Boolean value);
        partial void OnIsAdminChanged();
    
        /// <summary>
        /// Nessuna documentazione sui metadati disponibile.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion
    
    }

    #endregion
    
}
